#pragma once

class byte_code {
public:
    static const unsigned char POP_TOP = 1;
    static const unsigned char ROT_TWO = 2;
    static const unsigned char ROT_THREE = 3;
    static const unsigned char DUP_TOP = 4;
    static const unsigned char NOP = 9;
    static const unsigned char BINARY_MULTIPLY = 20;
    static const unsigned char BINARY_MODULO = 22;
    static const unsigned char BINARY_ADD = 23;
    static const unsigned char BINARY_SUBTRACT = 24;
    static const unsigned char BINARY_SUBSCR = 25;
    static const unsigned char BINARY_TRUE_DIVIDE = 27;
    static const unsigned char INPLACE_ADD = 55;
    static const unsigned char INPLACE_SUBTRACT = 56;
    static const unsigned char INPLACE_MULTIPLY = 57;
    static const unsigned char INPLACE_MODULO = 59;
    static const unsigned char STORE_SUBSCR = 60;
    static const unsigned char DELETE_SUBSCR = 61;
    static const unsigned char GET_ITER = 68;
    static const unsigned char LOAD_BUILD_CLASS = 71;
    static const unsigned char RETURN_VALUE = 83;
    // static const unsigned char YIELD_VALUE = 86;
    static const unsigned char POP_BLOCK = 87;
    static const unsigned char POP_EXCEPT = 89;
    static const unsigned char STORE_NAME = 90;
    static const unsigned char DELETE_NAME = 91;
    static const unsigned char UNPACK_SEQUENCE = 92;
    static const unsigned char FOR_ITER = 93;
    static const unsigned char STORE_ATTR = 95;
    static const unsigned char STORE_GLOBAL = 97;
    static const unsigned char ROT_N = 99;
    static const unsigned char LOAD_CONST = 100;
    static const unsigned char LOAD_NAME = 101;
    static const unsigned char BUILD_TUPLE = 102;
    static const unsigned char BUILD_LIST = 103;
    static const unsigned char BUILD_MAP = 105;
    static const unsigned char LOAD_ATTR = 106;
    static const unsigned char COMPARE_OP = 107;
    static const unsigned char IMPORT_NAME = 108;
    static const unsigned char IMPORT_FROM = 109;
    static const unsigned char JUMP_FORWARD = 110;
    static const unsigned char JUMP_ABSOLUTE = 113;
    static const unsigned char POP_JUMP_IF_FALSE = 114;
    static const unsigned char POP_JUMP_IF_TRUE = 115;
    static const unsigned char LOAD_GLOBAL = 116;
    static const unsigned char IS_OP = 117;
    static const unsigned char CONTAINS_OP = 118;
    //static const unsigned char RERAISE = 119;
    static const unsigned char JUMP_IF_NOT_EXC_MATCH = 121;
    static const unsigned char SETUP_FINALLY = 122;
    static const unsigned char LOAD_FAST = 124;
    static const unsigned char STORE_FAST = 125;
    static const unsigned char RAISE_VARARGS = 130;
    static const unsigned char CALL_FUNCTION = 131;
    static const unsigned char MAKE_FUNCTION = 132;
    static const unsigned char LOAD_CLOSURE = 135;
    static const unsigned char LOAD_DEREF = 136;
    static const unsigned char STORE_DEREF = 137;
    static const unsigned char CALL_FUNCTION_KW = 141;
    static const unsigned char FORMAT_VALUE = 155;
    static const unsigned char BUILD_CONST_KEY_MAP = 156;
    static const unsigned char BUILD_STRING = 157;
    static const unsigned char LOAD_METHOD = 160;
    static const unsigned char CALL_METHOD = 161;
    static const unsigned char LIST_EXTEND = 162;
    enum compare_op {
        LESS = 0,
        LESS_EQUAL = 1,
        EQUAL = 2,
        NOT_EQUAL = 3,
        GREATER = 4,
        GREATER_EQUAL = 5,
        IN = 6,
        NOT_IN = 7,
        IS = 8,
        IS_NOT = 9,
        EXC_MATCH = 10
    };
};
